server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: nan-picture-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nan_picture
    username: root
    password: 123456

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    #仅在开发环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      logic-delete-field: isDelete  #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: Knife4j官方文档
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.zn.nanpicturebackend.controller

#cos:
#  client:
#    host:
#    secretId:
#    secretKey:
#    region:
#    bucket: